### ISSUE TITLE
Clicking Start Stream, nothing happens

### ISSUE THREAD

**Issue by Aaronstephen** [peci1/lumix-link-desktop#10]
Via Control.bat connected succesfully with camera (G7). When clicking on Start Stream, nothing happens. Probably java is not connected correctly or something but how do i know.

**Comment by peci1** [comment]
Can you open the developer tools (F12 in Chrome or Firefox), switch to "Network" tab, and show me what happens when you click the start stream button? There should be a new request, which can either succeed (return code 200 or so), or fail (return code 400 or 500-like). If it succeeds, the developer tools allow you to display the reponse. I will need that.

Can you handle that?
